"""empty message

Revision ID: 88c78e4eece0
Revises: 8145d33c1543
Create Date: 2023-05-12 17:34:56.677042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c78e4eece0'
down_revision = '8145d33c1543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galaxy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinate_center_x', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('coordinate_center_y', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('coordinate_center_y')
        batch_op.drop_column('coordinate_center_x')

    op.drop_table('galaxy')
    # ### end Alembic commands ###
